# Generated by Django 5.0.4 on 2024-04-20 12:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=1000)),
                ('ItemName', models.CharField(max_length=500)),
                ('Cost', models.CharField(max_length=8)),
                ('OrderDateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSectionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=50)),
                ('EmailId', models.CharField(max_length=100)),
                ('MobileNumber', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('PinCode', models.CharField(max_length=6)),
                ('PaymentMethod', models.CharField(max_length=25)),
                ('CardName', models.CharField(max_length=30)),
                ('CardNumber', models.CharField(max_length=19)),
                ('CardExpiry', models.CharField(max_length=7)),
                ('Cvv', models.CharField(max_length=3)),
                ('PaymentDateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SignupSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=50)),
                ('MobileNumber', models.CharField(max_length=10, unique=True)),
                ('EmailId', models.CharField(default='', max_length=100, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('DateOfRegisteration', models.DateTimeField(default=django.utils.timezone.now)),
                ('UserLastUpdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Video_File', models.FileField(upload_to='videos')),
                ('Upload_DateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MobileNumber', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=50)),
                ('LoginDateTime', models.DateTimeField(auto_now=True)),
                ('LoginStatus', models.BooleanField(default=True)),
                ('User', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Food_Munch_App.signupsection')),
            ],
        ),
    ]
